# Generated by Django 3.1.6 on 2021-02-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='short_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre_corto'),
        ),
    ]
